### ISSUE TITLE
Changes required for upcoming CoffeeScript upgrade

### ISSUE THREAD

**Issue by maxbrunsfeld** [peele/plantuml-preview#25]
Hi! Thanks for maintaining the plantuml-preview package!

In Atom v1.12, we are going to [upgrade CoffeeScript](https://github.com/atom/atom/pull/12780) to the latest version. This upgrade entails one potentially breaking change to the language:

> Changed strategy for the generation of internal compiler variable names. Note that this means that @example function parameters are no longer available as naked example variables within the function body.

We think your package may be affected by this upgrade, in the following places:
- The `ext` variable [here](https://github.com/peele/plantuml-preview/tree/master/lib/plantuml-preview-view.coffee#L109)

These findings are based on linting packages with `coffeescope`. We could be wrong about some of them. When we release v1.12 beta, please test your package against it to make sure that it works. Let me know if you have any further questions; I will be happy to help!

**Comment by peele** [comment]
I ran coffeelint with following configuration and it did not highlight the line indicated above. Could the issue be in js-beautify? The same pattern was used for the clipboard and nativeimage variables. Any help you offer would be appreciated. 

```
{
  "max_line_length": {
    "name": "max_line_length",
    "level": "ignore"
  },
  "check_scope": {
    "module": "coffeescope2",
    "level": "warn",
    "environments": ["es5", "es6", "browser", "node", "jasmine"],
    "globals": {
      "atom": true,
      "afterEach": true,
      "beforeEach": true,
      "describe": true,
      "fdescribe": true,
      "xdescribe": true,
      "expect": true,
      "it": true,
      "fit": true,
      "xit": true,
      "jasmine": true,
      "runs": true,
      "spyOn": true,
      "waitsFor": true,
      "waitsForPromise": true,
      "indexedDB": true
    },
    "overwrite": false,
    "shadow": false,
    "shadow_builtins": false,
    "shadow_exceptions": ["err", "next"],
    "undefined": true,
    "hoist_local": true,
    "hoist_parent": true,
    "unused_variables": false,
    "unused_arguments": false,
    "unused_classes": true
  }
}
```

**Comment by maxbrunsfeld** [comment]
Oh, sorry for the relative URL. The file has changed since I ran the linter. Should have included the SHA. I was trying to link to [here](https://github.com/peele/plantuml-preview/blob/9f8ba77696937fbfdcd9f310895c5e9a77139289/lib/plantuml-preview-view.coffee#L116). It looks like `ext` is never defined. You may want to fix that, though it's probably not urgent.

That said, I don't think this actually has to do with the coffee-script upgrade. Sorry for the confusion.
