### ISSUE TITLE
Notifications are Useless & Unnecessary 

### ISSUE THREAD

**Issue by eduncan911** [peele/plantuml-preview#31]
When a syntax error occurs, which happens a lot with PlantUML - especially with `newpage` and trying to mesh things together, this is what I see:

![image](https://cloud.githubusercontent.com/assets/104980/23332870/cec99504-fb4e-11e6-92f5-2b2b9dd3a8b5.png)

As you can see, the actual REAL error message is displayed instead of the SVG/PNG image.  That's perfectly fine and expected.

Except... There's a big fat red Notification window sitting on top that gives me NO error reasons and blocks my view (no to mention, forcing me to "Dismiss" it constantly).  

I think I tracked this down to this line of code:

https://github.com/peele/plantuml-preview/blob/f6027c72e02dbba4bcd794b0195dfeb365b45064/lib/plantuml-preview-view.coffee#L335

Commenting that line of code fixes the issue for me. 

It does not display any error information either. Just telling me to go look at the Console for more info.  

--

Suggestion:

Don't display the notification / remove it.  If there is any error at all, continue with showing the error in the preview window.

Open to other discussions.

**Comment by peele** [comment]
Actually have some stashed changes, from 6 months ago or so, for removing all the notification windows and still provide informative error messages. Will have to revisit.
