### ISSUE TITLE
HTMLDocument.registerElement is deprecated.

### ISSUE THREAD

**Issue by StUjeen** [peele/plantuml-preview#47]
Hi!

I use plantuml-preview package and trying to toggle preview command with Ctrl+Alt+P no results and have this deprecation only:

Use `customElements.define` instead of `document.registerElement` see https://javascript.info/custom-elements
```
HTMLDocument.registerElement (file:///C:/Users/4737151/AppData/Local/atom/app-1.63.0/resources/app.asar/static/index.js:160:12)
registerElement (C:\Users\4737151\.atom\packages\plantuml-preview\node_modules\space-pen\lib\space-pen.js:66:88)
Builder.openTag (C:\Users\4737151\.atom\packages\plantuml-preview\node_modules\space-pen\lib\space-pen.js:297:27)
Builder.tag (C:\Users\4737151\.atom\packages\plantuml-preview\node_modules\space-pen\lib\space-pen.js:274:12)
Function.div (C:\Users\4737151\.atom\packages\plantuml-preview\node_modules\space-pen\lib\space-pen.js:83:49)
Function.content (C:\Users\4737151\.atom\packages\plantuml-preview\lib\plantuml-preview-view.coffee:60:19)
```

Win 11, Atom version 1.63.0

![image](https://user-images.githubusercontent.com/29988773/202936907-99889d6a-b943-49e9-b6b3-14f47d09ae4b.png)

**Comment by ArgonX3** [comment]
Plaese, can someone resolve this problem? I use atom only for this plug-in.

**Comment by StUjeen** [comment]
> Plaese, can someone resolve this problem? I use atom only for this plug-in.

No one replied so far! I started to use VS Code, there is plantUML plugin and works even better

**Comment by zanedp** [comment]
Atom was "sunset" on December 15: https://github.blog/2022-06-08-sunsetting-atom/, and I think most Atom plugins are probably being abandoned.

Switching to VS Code is a pretty good alternative. There are several PlantUML extensions available for it.
